version: '3.8'

services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    environment:
      - DATABASE_URL=sqlite:/data/finance.db

volumes:
  db_data:
