

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the source code
      - .:/usr/src/app
      # Persist the cargo registry and target folder
      - cargo_registry:/usr/local/cargo/registry
      - cargo_target:/usr/src/app/target
      # Persist the database
      - db_data:/data
    environment:
      - DATABASE_URL=sqlite:/data/finance.db
      - CARGO_HOME=/usr/local/cargo
    # Keep the container running
    tty: true

volumes:
  cargo_registry:
  cargo_target:
  db_data: